language: python
python:
  - '3.4'
sudo: false
script: ./build.py --vitamin
after_success: 
  - git mv export search/export
  - git commit -a -m "publish redpanda.json in search directory"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master
